# Generated by Django 4.2.1 on 2023-05-26 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ResumeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('DOB', models.DateTimeField()),
                ('address', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=4)),
                ('contry', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('link', models.CharField(max_length=300)),
                ('project_name', models.CharField(max_length=100)),
                ('project_desc', models.CharField(max_length=100)),
                ('college', models.CharField(max_length=100)),
                ('degree', models.CharField(max_length=100)),
                ('course_name', models.CharField(max_length=100)),
                ('source', models.CharField(max_length=100)),
                ('skill', models.CharField(max_length=50)),
                ('hobby', models.CharField(max_length=50)),
                ('company_name', models.CharField(max_length=100)),
                ('Experience', models.CharField(max_length=10)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
            ],
        ),
    ]
